modLoader = "javafml" #mandatory
loaderVersion = "[4,)" #mandatory
license = "All Rights Reserved" # Review your options at https://choosealicense.com/.
issueTrackerURL = "https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap/issues"
[[mods]] #mandatory
modId = "xaerominimap" #mandatory
version = "25.3.10" #mandatory
displayName = "Xaero's Minimap" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional (see https://docs.neoforged.net/docs/misc/updatechecker/)
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional (displayed in the mod UI)
credits="" #optional
authors = "xaero96" #optional
description = '''The most vanilla-looking minimap for Minecraft.''' #mandatory (Supports multiline text)
[[mixins]]
config = "xaerohud.mixins.json"
[[mixins]]
config = "xaerohud.neoforge.mixins.json"
[[mixins]]
config = "xaerominimap.mixins.json"
[[mixins]]
config = "xaerominimap.neoforge.mixins.json"
[[dependencies.xaerominimap]] #optional
modId = "neoforge" #mandatory
type="required" #mandatory (Can be one of "required", "optional", "incompatible" or "discouraged")
versionRange = "[21.0.110-beta,)" #mandatory
ordering = "NONE" # The order that this dependency should load in relation to your mod, required to be either 'BEFORE' or 'AFTER' if the dependency is not mandatory
side = "BOTH" # Side this dependency is applied on - 'BOTH', 'CLIENT' or 'SERVER'
[[dependencies.xaerominimap]]
modId = "minecraft"
type="required" #mandatory (Can be one of "required", "optional", "incompatible" or "discouraged")
versionRange = "1.21.1"
ordering = "NONE"
side = "BOTH"
[[dependencies.xaerominimap]]
modId = "openpartiesandclaims"
type="optional"
versionRange = "[0.14.0,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.xaerominimap]]
modId = "xaeroworldmap"
type="optional"
versionRange = "[1.40.2,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.xaerobetterpvp]]
modId = "xaerolib"
type="required"
versionRange = "[1.0.50,)"
ordering = "NONE"
side = "BOTH"

# Features are specific properties of the game environment, that you may want to declare you require. This example declares
# that your mod requires GL version 3.2 or higher. Other features will be added. They are side aware so declaring this won't
# stop your mod loading on the server for example.
#[features.xaerominimap]
#openGLVersion="[3.2,)"